### ISSUE TITLE
Loaded counts are misleading

### ISSUE THREAD

**Issue by vanderaj** [Freaky/elite_shield_tester#2]
I wanted to load the full set of boosters, but when I tried to use the --booster-csv option, it didn't load all 20, just 8. 

```
PS C:\Users\vande\GitHub\elite_shield_tester\target\debug>  .\elite_shield_tester.exe -t 0 -k 0 -s 8 -d .30 -e 0 -a 10 --booster-csv C:\Users\vande\GitHub\D2EA_Shield_tester\ShieldBoosterVariants.csv
Elite Shield Tester Rust Edition v0.4.1
Custom Booster CSV: C:\Users\vande\GitHub\D2EA_Shield_tester\ShieldBoosterVariants.csv
Loaded 45 shields and 8 boosters
Tested 289575 loadouts in 18.17ms
```

**Comment by Freaky** [comment]
It's filtering out resistance boosters, because your projected damage type is all absolute.  You'll note it goes up to 12 boosters if you add thermal damage, and 16 if you add kinetic or explosive.

Use `--disable-filter` if you want it to do an exhaustive check.

**Comment by Freaky** [comment]
Fixed in latest release, ta :)
