### ISSUE TITLE
Shield cell bank hit points shown as part of Shield hit points

### ISSUE THREAD

**Issue by DownToEarthAstronomy** [Freaky/elite_shield_tester#3]
In the final report the hit points from the SCB are calculated into the ship hit points. While this is correct when testing it can be misleading when people look at the stats of the ship.

Elite Shield Tester Rust Edition v0.4.1
Loaded 45 shields and 25 boosters
Tested 15339780 loadouts in 194.90ms

---- TEST SETUP ----

      Shield Boosters: 7
     **Shield Cell Bank: 10000.0 Mj**
Guardian Shield Reinf: 0.0 Mj
    Prismatic Shields: yes
     Regen Time Limit: no
        Explosive DPS: 18
          Kinetic DPS: 30
          Thermal DPS: 30
         Absolute DPS: 0
 Damage Effectiveness: 50.0%

---- TEST RESULTS ----

Survival Time   : 1232.8 s
Shield Generator: Bi-Weave - Thermal Resistance - Force Block
Shield Booster 1: Resistance Augmented - Thermo Block
               2: Resistance Augmented - Force Block
               3: Resistance Augmented - Force Block
               4: Resistance Augmented - Force Block
               5: Resistance Augmented - Force Block
               6: Resistance Augmented - Force Block
               7: Resistance Augmented - Force Block

    **Shield Hitpoints: 11100 Mj**
   Shield Regen Rate: 4.4 Mj/s (1261.4s from 50%)
Explosive Resistance: +75.7% (45709 Mj)
  Kinetic Resistance: +68.9% (35640 Mj)
  Thermal Resistance: +71.0% (38305 Mj)

**Comment by Freaky** [comment]
Fixed in latest release, thanks :)
