### ISSUE TITLE
Damage effectiveness stuck on 50%

### ISSUE THREAD

**Issue by lmwslm** [Freaky/elite_shield_tester#6]
Damage effectiveness can't be changed from 50% using the slider. It is always set back to 50% in the results no matter what you do with the slider.

It seems that the slider reverts back to 50% when any other field is changed. To get around this, I tried setting damage effectiveness last but even though the slider didn't move back to 50%, the results still showed it was set to 50%.

This occurs on multiple devices and browsers for me.

**Comment by Freaky** [comment]
Well spotted, fix committed, thanks :)
